// Generated by scripts/build-site.cjs. Cache only this quiz, never other sites.
const PREFIX = 'top-quiz:' + self.registration.scope;
const CACHE = PREFIX + ':94fd693d2f96';
const URLS = [self.registration.scope, new URL('index.html', self.registration.scope).href];
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(URLS)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith(PREFIX + ':') && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET' || !URLS.includes(event.request.url.split(/[?#]/)[0])) return;
  // The installed cache is a complete version; upgrades install atomically.
  event.respondWith(caches.open(CACHE).then(async cache => (await cache.match(event.request, {ignoreSearch: true})) || fetch(event.request)));
});
