const {test,expect}=require('@playwright/test');
const {pathToFileURL}=require('node:url');
const url=pathToFileURL(require('node:path').resolve('The Top Quiz.html')).href;
async function open(page){await page.goto('about:blank');await page.clock.install();if(process.env.QUIZ_INLINE_TEST==='1')await page.setContent(require('node:fs').readFileSync('The Top Quiz.html','utf8'));else await page.goto(url);await page.getByRole('button',{name:'Start flight'}).click();}
async function choose(page,sign=1){await page.clock.runFor(300);const id=await page.evaluate(sign=>{const q=QuizCore.questions[Number(document.querySelector('[data-question]').dataset.question)];return q.options.find(o=>Math.sign(o.traits.reduce((s,n,i)=>s+n*[2,1,-2,-1][i],0))===sign).id},sign);await page.locator(`[data-option="${id}"]`).click();}
for(const sign of [1,-1])test(`offline full quiz reveals ${sign===1?'Maverick':'Goose'}`,async({page,context})=>{const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url())});await context.setOffline(true);await open(page);for(let i=0;i<15;i++)await choose(page,sign);await expect(page.getByRole('heading',{name:sign===1?'Maverick':'Goose',exact:true})).toBeVisible();expect(errors).toEqual([]);expect(requests).toEqual([]);await page.getByRole('button',{name:'Fly again'}).click();await expect(page.getByRole('button',{name:'Start flight'})).toBeVisible();});
test('warning, mute, expiry, and too few answers',async({page})=>{await open(page);await page.clock.runFor(14900);await expect(page.locator('#timer')).toHaveText('6');await page.clock.runFor(100);await expect(page.locator('#timer')).toHaveText('5');await expect(page.locator('#timer-wrap')).toHaveClass(/urgent/);await page.getByRole('button',{name:/Mute sound/}).click();await expect(page.getByRole('button',{name:/Enable sound/})).toBeVisible();await page.clock.runFor(5800);await expect(page.locator('[data-question]')).toHaveAttribute('data-question','1');for(let i=1;i<15;i++)await page.clock.runFor(20800);await expect(page.getByRole('heading',{name:'One more flight?'})).toBeVisible();});
test('nine answered questions retry; ten answered questions reveal',async({page})=>{for(const count of [9,10]){await open(page);for(let i=0;i<count;i++)await choose(page);for(let i=count;i<15;i++)await page.clock.runFor(20800);await expect(page.getByRole('heading',{name:count===9?'One more flight?':'Maverick',exact:true})).toBeVisible();}});
test('double taps do not skip a question',async({page})=>{await open(page);await page.clock.runFor(300);await page.locator('[data-option]').first().dblclick();await expect(page.locator('[data-question]')).toHaveAttribute('data-question','1');});
test('background expiry does not consume unseen questions',async({page})=>{await open(page);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))});await page.clock.runFor(90000);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'))});await page.clock.runFor(800);await expect(page.locator('[data-question]')).toHaveAttribute('data-question','1');await expect(page.locator('#timer')).toHaveText('20');});
for(const [width,height] of [[360,640],[390,844],[320,568],[844,390]])test(`phone layout ${width}x${height}`,async({page})=>{await page.setViewportSize({width,height});await open(page);for(let i=0;i<15;i++){const buttons=page.locator('[data-option]');for(const button of await buttons.all()){const box=await button.boundingBox();expect(box.height).toBeGreaterThanOrEqual(48);if(height>=640){expect(box.y).toBeGreaterThanOrEqual(0);expect(box.y+box.height).toBeLessThanOrEqual(height);}}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await choose(page);}});
test('audio unavailable still completes; enlarged text and keyboard work',async({page})=>{await page.addInitScript(()=>{window.AudioContext=undefined;window.webkitAudioContext=undefined});await page.emulateMedia({reducedMotion:'reduce'});await open(page);await expect(page.locator('#sound')).toHaveText('Sound unavailable');await page.addStyleTag({content:'html {font-size: 24px}'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.clock.runFor(300);await page.locator('[data-option]').first().focus();await page.keyboard.press('Enter');await expect(page.locator('[data-question]')).toHaveAttribute('data-question','1');for(let i=1;i<15;i++)await choose(page);await expect(page.locator('.result-name')).toBeVisible();});
test('synthesized tones start at five seconds and stop on mute and answer',async({page})=>{
 await page.addInitScript(()=>{window.__tones=[];window.AudioContext=class{constructor(){this.state='running';this.destination={}}get currentTime(){return performance.now()/1000}resume(){return Promise.resolve()}createGain(){return{gain:{setValueAtTime(){},linearRampToValueAtTime(){}},connect(){},disconnect(){}}}createOscillator(){const t={frequency:{value:0},connect(){},disconnect(){},start(at){this.startAt=at},stop(at){if(at===undefined)this.cancelled=true;else this.stopAt=at}};window.__tones.push(t);return t}}});
 await open(page);await page.clock.runFor(14900);expect(await page.evaluate(()=>__tones.length)).toBe(0);await page.clock.runFor(100);expect(await page.evaluate(()=>__tones.length)).toBe(2);expect(await page.evaluate(()=>__tones.every(t=>t.stopAt-t.startAt<=.051))).toBe(true);await page.getByRole('button',{name:'Mute sound'}).click();expect(await page.evaluate(()=>__tones.every(t=>t.cancelled))).toBe(true);await page.clock.runFor(1000);expect(await page.evaluate(()=>__tones.length)).toBe(2);await page.getByRole('button',{name:'Enable sound'}).click();await page.clock.runFor(50);await choose(page);expect(await page.evaluate(()=>__tones.every(t=>t.cancelled))).toBe(true);
});
test('a real twenty-second deadline advances once',async({page})=>{await page.goto('about:blank');if(process.env.QUIZ_INLINE_TEST==='1')await page.setContent(require('node:fs').readFileSync('The Top Quiz.html','utf8'));else await page.goto(url);await page.getByRole('button',{name:'Start flight'}).click();await expect(page.locator('[data-question]')).toHaveAttribute('data-question','1',{timeout:23000});await expect(page.locator('#timer')).toHaveText('20');});
