// Keep the downloadable quiz as the single source. No bundler or runtime library.
const fs = require('node:fs');
const {createHash} = require('node:crypto');
const source = fs.readFileSync('The Top Quiz.html', 'utf8');
const offlineScript = `
<script>
// Failure to save offline must never stop someone taking the quiz.
(async () => {
  const status = document.getElementById('offline-status');
  try {
    if (!('serviceWorker' in navigator)) throw new Error('Unsupported');
    await navigator.serviceWorker.register('./sw.js');
    await navigator.serviceWorker.ready;
    if (!navigator.serviceWorker.controller) {
      await new Promise(resolve => navigator.serviceWorker.addEventListener('controllerchange', resolve, {once: true}));
    }
    status.textContent = 'Ready for offline use.';
  } catch {
    status.textContent = 'Quiz ready. Offline saving is unavailable in this browser.';
  }
})();
</script>`;
const html = source
  .replace('<meta name="theme-color"', '<meta name="apple-mobile-web-app-capable" content="yes">\n<meta name="apple-mobile-web-app-title" content="The Top Quiz">\n<meta name="theme-color"')
  .replace('<main id="app"></main>', '<main id="app"><p>Loading your flight check…</p><noscript><p>Open this link in Safari or Chrome with JavaScript enabled to take the quiz.</p></noscript></main>')
  .replace('<strong>100%</strong><span>Offline</span>', '<strong>5 min</strong><span>Your flight</span>')
  .replace('<footer>NO SIGNAL NEEDED. JUST INSTINCT.</footer>', '<footer><p id="offline-status" role="status" style="font-size:.75rem">Preparing offline access…</p>JUST INSTINCT. NO SIGN-UP.</footer>')
  .replace('</body>', offlineScript + '\n</body>');
const version = createHash('sha256').update(html).digest('hex').slice(0, 12);
const worker = `// Generated by scripts/build-site.cjs. Cache only this quiz, never other sites.
const PREFIX = 'top-quiz:' + self.registration.scope;
const CACHE = PREFIX + ':${version}';
const URLS = [self.registration.scope, new URL('index.html', self.registration.scope).href];
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(URLS)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith(PREFIX + ':') && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET' || !URLS.includes(event.request.url.split(/[?#]/)[0])) return;
  // The installed cache is a complete version; upgrades install atomically.
  event.respondWith(caches.open(CACHE).then(async cache => (await cache.match(event.request, {ignoreSearch: true})) || fetch(event.request)));
});
`;
fs.writeFileSync('index.html', html);
fs.writeFileSync('sw.js', worker);
fs.writeFileSync('.nojekyll', '');
console.log('Built GitHub Pages site and versioned offline cache:', version);
